#!/bin/bash

steamfolder="/home/$USER/.steam/steam/compatibilitytools.d/"
lutrisfolder="/home/$USER/.local/share/lutris/runners/wine/"
protonGE="https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton9-23/GE-Proton9-23.tar.gz"
wineGE="https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz"

echo "Welcome to protonwine, your terminal tool to install Proton-GE and Wine-GE for Steam and Lutris!"
sleep 3s

echo "Do you want to install PROTON-GE or WINE-GE? (answer with either p or w since this is case-sensitive): "
read input1

if [[ $input1 != w && $input1 != p ]]; then
    echo "Error, please run the program again."
fi

echo "You chose: $input1"
sleep 3s

if [[ $input1 = "p" ]]; then

    echo "Do you want to install PROTON-GE for Lutris or Steam? (l/s): "
    read input2

    echo "You chose: $input2"

    if [[ $input2 = "s" ]]; then
        echo "checking if Steam folder to install PROTON-GE exists, otherwise it will be created.."
        sleep 3s
    if [[ -d $steamfolder ]]; then
        echo "Looks like the required folder already exists, proceeding to install PROTON-GE.."
        sleep 3s
        cd $steamfolder
        curl -LJO $protonGE
        echo "Finished downloading the tar archive, proceeding to extract.."
        sleep 3s
        tar -xf GE-Proton9-23.tar.gz
        rm GE-Proton9-23.tar.gz
        echo "Done, you can now open Steam and select Proton-GE as a compatibility tool."

    else
        echo "Looks like the required folder doesn't exist, i'm going to create it.."
        mkdir -p $steamfolder
        cd $steamfolder
        curl -LJO $protonGE
        echo "Finished downloading the tar archive, proceeding to extract.."
        sleep 3s
        tar -xf GE-Proton9-23.tar.gz
        rm GE-Proton9-23.tar.gz
        echo "Done, you can now open Steam and select Proton-GE as a compatibility tool."
    fi
    fi
    fi

    if [[ $input2 = "l" ]]; then
        echo "i'm going to check if the required folder for PROTON-GE exists, otherwise i'm going to create it.."
        sleep 1s
        if [[ -d $lutrisfolder ]]; then
            echo "Looks like the required folder already exists, i'm going to install Proton-GE.."
            sleep 3s
            cd $lutrisfolder
            curl -LJO $protonGE
            echo "Finished downloading the tar archive, proceeding to extract.."
            sleep 3s
            tar -xf GE-Proton9-23.tar.gz
            rm GE-Proton9-23.tar.gz
            echo "Done, you can now open Lutris and select Proton-GE as a runner in the Wine section."
        else
            echo "Looks like the folder doesn't exist, i'm going to create it.."
            mkdir -p $lutrisfolder
            cd $lutrisfolder
            curl -LJO $protonGE
            echo "Finished downloading the tar archive, proceeding to extract.."
            sleep 3s
            tar -xf GE-Proton9-23.tar.gz
            rm GE-Proton9-23.tar.gz
            echo "Done, you can now open Lutris and select Proton-GE as a runner in the Wine section."
    fi
    fi
if [[ $input1 = "w" ]]; then
    echo "I'm going to check if Lutris folder to install Wine-GE exists, otherwise i'm going to create it.."
    sleep 3s

if [[ -d $lutrisfolder ]]; then
	echo "Looks like the required folder already exists, proceeding to install Wine-GE..."
    sleep 3s
    cd $lutrisfolder
    curl -LJO $wineGE
    echo "Finished downloading the tar archive, proceeding to extract.."
    sleep 3s
    tar -xf wine-lutris-GE-Proton8-26-x86_64.tar.xz
    rm wine-lutris-GE-Proton8-26-x86_64.tar.xz
    echo "Done, you can now open Lutris and select Wine-GE as a runner in the Wine section."
else
    echo "Looks like the required folder doesn't exist, proceeding to create it and then install Wine-GE.."
    mkdir -p $lutrisfolder
    cd $lutrisfolder
    curl -LJO $wineGE
    echo "Finished downloading the tar archive, proceeding to extract.."
    sleep 3s
    tar -xf wine-lutris-GE-Proton8-26-x86_64.tar.xz
    rm wine-lutris-GE-Proton8-26-x86_64.tar.xz
    echo "Done, you can now open Lutris and select Wine-GE as a runner in the Wine section."
fi
fi


